title: FEEDS.
description: "Blog Modern & Flat dengan Ionic v8 + Jekyll"
url: "https://mia-miaaw.github.io"
baseurl: "/blog"
license_key: "<%= ENV['license_key'] %>"

# Konfigurasi Iklan
custom_ads:
  image_url: "https://via.placeholder.com/400x250"
  target_url: "https://toko-kamu.com/promo"

# Permalinks
permalink: /blog/:title/

# Exclude files
exclude:
  - Gemfile.lock
  - node_modules/
  - vendor/
