title: FEEDS.
description: "Blog Modern & Flat dengan Ionic v8 + Jekyll"
url: "https://mia-miaaw.github.io"
baseurl: "/blog"
license_key: "<%= ENV['license_key'] %>"

# Konfigurasi Iklan
custom_ads:
  image_url: "https://s3.cdnppp789.com/uploads/1003/162ed9ff5afd4975c66ea061ec9516fa.png"
  target_url: "https://jp6789x2.com/s/BCE151027183"

# Permalinks
permalink: /blog/:title/

# Exclude files
exclude:
  - Gemfile.lock
  - node_modules/
  - vendor/
